# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'Client'
        db.create_table(u'MHDC_client', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user', self.gf('django.db.models.fields.related.OneToOneField')(to=orm['auth.User'], unique=True)),
            ('email_address', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('password', self.gf('django.db.models.fields.CharField')(max_length=32)),
            ('first_name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('last_name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('middle_initial', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('DOB', self.gf('django.db.models.fields.DateField')()),
            ('veteran', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('disablility', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('race', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('SSN', self.gf('django.db.models.fields.CharField')(max_length=9)),
            ('Ph_day', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Ph_evening', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Ph_cell', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Mailing_address', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Mailing_city', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Mailing_county', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Mailing_State', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Mailing_Zip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('Physical_address', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Physical_city', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Physical_county', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Physical_State', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Physical_Zip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('Years_There', self.gf('django.db.models.fields.CharField')(max_length=2)),
        ))
        db.send_create_signal(u'MHDC', ['Client'])

        # Adding model 'SelfHelpApplication'
        db.create_table(u'MHDC_selfhelpapplication', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('client', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['MHDC.Client'])),
            ('status', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('dateRecieved', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('appPrevAddress', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('appPrevCity', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('appPrevZip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('appEmployerName', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('appEmployerAddress', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('appEmployerprevCity', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('appEmployerprevZip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('appYearsThere', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('co_first_name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_last_name', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_middle_initial', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('co_DOB', self.gf('django.db.models.fields.DateField')()),
            ('co_SSN', self.gf('django.db.models.fields.CharField')(max_length=9)),
            ('co_Ph_day', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('co_Ph_evening', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('co_Ph_cell', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('co_Mailing_address', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_Mailing_city', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_Mailing_county', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_Mailing_State', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_Mailing_Zip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('co_Years_There', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('co_appPrevAddress', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('co_appPrevCity', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('co_appPrevZip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('co_appEmployerName', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('co_appEmployerAddress', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('co_appEmployerprevCity', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('co_appEmployerprevZip', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('co_appYearsThere', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('totalHousehold', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('crowdedHouse', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('numBedrooms', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('disabilities', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('homeOwner', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('deed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('currentArea', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('referral', self.gf('django.db.models.fields.CharField')(max_length=100)),
        ))
        db.send_create_signal(u'MHDC', ['SelfHelpApplication'])

        # Adding model 'DocCheckList'
        db.create_table(u'MHDC_docchecklist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('bankStatements', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('payStubs', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('taxForms', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('childSupport', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('moneyOrder', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('picID', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('landlordContact', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('socialSecurity', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('foodAssistance', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('TANF', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('divorce', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('bankruptcy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('alimony', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'MHDC', ['DocCheckList'])

        # Adding model 'SelfHelpStaffChecklist'
        db.create_table(u'MHDC_selfhelpstaffchecklist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('currentArea', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('ami', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('orientation_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('orientation_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('creditPlan_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('creditPlan_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('docCheckList_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('docCheckList_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('counselSession_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('counselSession_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('totalCreditReview_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('totalCreditReview_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('updatePaystubs_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('updatePaystubs_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('assets_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('assets_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('recentPaystubs_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('recentPaystubs_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('recentTaxes_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('recentTaxes_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('childSupportOrder_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('childSupportOrder_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('childSupportHistory_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('childSupportHistory_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('picIDs_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('picIDs_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('socialSecurityLetter_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('socialSecurityLetter_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('monthlyPension_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('monthlyPension_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('purchaseOfCare_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('purchaseOfCare_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('foodAssistance_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('foodAssistance_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('tanfLetter_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('tanfLetter_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('divorce_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('divorce_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('bankruptcy_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('bankruptcy_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('alimony_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('alimony_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('mortgage_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('mortgage_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('release_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('release_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('ifIneligible_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('ifIneligible_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('ifEligible_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('ifEligible_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('eligibility_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('eligibility_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('totalApplication_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('totalApplication_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('requestEstimate_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('requestEstimate_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('constructionDocumentation_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('constructionDocumentation_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('usdaAppraisalRequest_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('usdaAppraisalRequest_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('usdaInterview_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('usdaInterview_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('scheduleClosing_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('scheduleClosing_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('requestSurvey_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('requestSurvey_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('requestTitle_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('requestTitle_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('forwardSurvey_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('forwardSurvey_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('reviewHUD_dateComplete', self.gf('django.db.models.fields.CharField')(max_length=11)),
            ('reviewHUD_signature', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'MHDC', ['SelfHelpStaffChecklist'])

        # Adding model 'Home_Repair'
        db.create_table(u'MHDC_home_repair', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Home_owners_insurance', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Own_multiple_props', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Property_taxes_uptodate_city', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Property_taxes_uptodate_county', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Mortage', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('Reverse_mortage', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('Dwelling_type', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('Own_dwelling', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Develpment', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('Previous_client', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Previous_when', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('Work_completed_by_HRP', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('Referred_to_HRP_by', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('Applied_to', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('Emergengy_Repair', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('Furnace_Issues', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Eletric_Issues', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Plumbing_Issues', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Carbon_monoxide_detectors_needed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Smoke_detectors_needed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('appliances', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('Estimated_annual_income', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Max_income_for_people', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('Max_income_per_person', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Mo_income_SS', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Mo_income_SSDI', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Mo_income_Food_Assist', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Mo_income_TANF', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Package_mailed', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Package_returned', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Verified_Home_ownership', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Total_Monthly', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('HRP_Approved', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('HRP_Denied', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('Denial_or_approval_explanation', self.gf('django.db.models.fields.CharField')(max_length=1000)),
            ('Contact_notes', self.gf('django.db.models.fields.CharField')(max_length=4000)),
        ))
        db.send_create_signal(u'MHDC', ['Home_Repair'])

        # Adding model 'Living_In_Home'
        db.create_table(u'MHDC_living_in_home', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('relationship', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('DOB', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Disabled', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'MHDC', ['Living_In_Home'])

        # Adding model 'Month_1'
        db.create_table(u'MHDC_month_1', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Income_from_Employment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Unemployment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('TANF_Food_Stamps', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Alimony_Child_support', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('SSI_Disability', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Savings_account', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Rental_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Pension_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Total', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal(u'MHDC', ['Month_1'])

        # Adding model 'Month_2'
        db.create_table(u'MHDC_month_2', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Income_from_Employment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Unemployment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('TANF_Food_Stamps', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Alimony_Child_support', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('SSI_Disability', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Savings_account', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Rental_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Pension_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Total', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal(u'MHDC', ['Month_2'])

        # Adding model 'Month_3'
        db.create_table(u'MHDC_month_3', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Income_from_Employment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Unemployment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('TANF_Food_Stamps', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Alimony_Child_support', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('SSI_Disability', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Savings_account', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Rental_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Pension_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Total', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal(u'MHDC', ['Month_3'])

        # Adding model 'Month_4'
        db.create_table(u'MHDC_month_4', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Income_from_Employment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Unemployment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('TANF_Food_Stamps', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Alimony_Child_support', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('SSI_Disability', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Savings_account', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Rental_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Pension_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Total', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal(u'MHDC', ['Month_4'])

        # Adding model 'Month_5'
        db.create_table(u'MHDC_month_5', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Income_from_Employment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Unemployment', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('TANF_Food_Stamps', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Alimony_Child_support', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('SSI_Disability', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Savings_account', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Rental_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Pension_income', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('Total', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal(u'MHDC', ['Month_5'])

        # Adding model 'Repair_Checklist'
        db.create_table(u'MHDC_repair_checklist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Deed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Title_mobile_home', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Most_recent_paystubs', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Verification_of_unemployment_income', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Federal_tax_returns', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Child_support_court_order_12_month_history', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Drivers_license_identificaton', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Rental_income', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Current_Social_Security_Disability_Award_leter', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Purchase_of_care_letter', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Food_assistance_Letter', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('TANF_letter', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Divorce_Decree', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Bankruptcy_Documentation', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Alimony', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Letter_of_Medical_Necessity_for_Ramps', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Copy_of_cleaning_for_furnace', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('County_CDBG_referral_form', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'MHDC', ['Repair_Checklist'])

        # Adding model 'Repair_Internal_Checklist'
        db.create_table(u'MHDC_repair_internal_checklist', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('Intake_form', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Eligibility_Packet_Sent', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Total_Eligibility_Packet_received', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Deed', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Deed_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Copy_of_Property_Taxes', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Copy_of_Property_Taxes_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Two_months_bank_Statements', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Two_months_bank_Statements_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Six_recent_Pay_stubs', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Six_recent_Pay_stubs_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Federal_Taxes_two_years', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Federal_Taxes_two_years_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Child_Support_Court_Order', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Child_Support_Court_Order_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Child_Support_History', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Child_Support_History_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Copy_of_Drivers_license', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Copy_of_Drivers_license_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Disability_Award_letter', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Disability_Award_letter_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Monthly_Pension_Statements', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Monthly_Pension_Statements_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Purchase_Care_Letter', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Purchase_Care_Letter_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Food_Assistance_Letter', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Food_Assistance_Letter_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('TANF_letter', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('TANF_letter_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Divorce_Decree', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Divorce_Decree_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Bankruptcy_Discharge_Documentation', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Bankruptcy_Discharge_Documentation_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Alimony', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Alimony_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Mortage_Statement', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Mortage_Statement_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Authorization_Release_Info', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Authorization_Release_Info_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Income_Elibility_Determined', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Denial_letter_sent', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Denial_letter_sent_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Client_file_passed', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Preservation_Manager_calls', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Preservation_Manager_calls_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Site_visit_worksheet', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Site_visit_worksheet_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Photos_of_dwelling', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Photos_of_dwelling_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Prepare_presentation_committee', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Approved_or_Denied', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Spreadsheet_on_server', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Letter_sent', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Letter_sent_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Appoinment_with_client', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Appoinment_with_client_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Invoices_given_to_PCP', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Invoices_given_to_PCP_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Submit_invoices_to_AD', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Submit_invoices_to_AD_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('Finalize_payment_requests', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('Finalize_payment_requests_upload', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'MHDC', ['Repair_Internal_Checklist'])


    def backwards(self, orm):
        
        # Deleting model 'Client'
        db.delete_table(u'MHDC_client')

        # Deleting model 'SelfHelpApplication'
        db.delete_table(u'MHDC_selfhelpapplication')

        # Deleting model 'DocCheckList'
        db.delete_table(u'MHDC_docchecklist')

        # Deleting model 'SelfHelpStaffChecklist'
        db.delete_table(u'MHDC_selfhelpstaffchecklist')

        # Deleting model 'Home_Repair'
        db.delete_table(u'MHDC_home_repair')

        # Deleting model 'Living_In_Home'
        db.delete_table(u'MHDC_living_in_home')

        # Deleting model 'Month_1'
        db.delete_table(u'MHDC_month_1')

        # Deleting model 'Month_2'
        db.delete_table(u'MHDC_month_2')

        # Deleting model 'Month_3'
        db.delete_table(u'MHDC_month_3')

        # Deleting model 'Month_4'
        db.delete_table(u'MHDC_month_4')

        # Deleting model 'Month_5'
        db.delete_table(u'MHDC_month_5')

        # Deleting model 'Repair_Checklist'
        db.delete_table(u'MHDC_repair_checklist')

        # Deleting model 'Repair_Internal_Checklist'
        db.delete_table(u'MHDC_repair_internal_checklist')


    models = {
        u'MHDC.client': {
            'DOB': ('django.db.models.fields.DateField', [], {}),
            'Mailing_State': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Mailing_Zip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'Mailing_address': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Mailing_city': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Mailing_county': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Meta': {'object_name': 'Client'},
            'Ph_cell': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Ph_day': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Ph_evening': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Physical_State': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Physical_Zip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'Physical_address': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Physical_city': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Physical_county': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'SSN': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'Years_There': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'disablility': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'email_address': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'middle_initial': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '32'}),
            'race': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True'}),
            'veteran': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'MHDC.docchecklist': {
            'Meta': {'object_name': 'DocCheckList'},
            'TANF': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'alimony': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'bankStatements': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'bankruptcy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'childSupport': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'divorce': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'foodAssistance': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'landlordContact': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'moneyOrder': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'payStubs': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'picID': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'socialSecurity': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'taxForms': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'MHDC.home_repair': {
            'Applied_to': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'Carbon_monoxide_detectors_needed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Contact_notes': ('django.db.models.fields.CharField', [], {'max_length': '4000'}),
            'Denial_or_approval_explanation': ('django.db.models.fields.CharField', [], {'max_length': '1000'}),
            'Develpment': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'Dwelling_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'Eletric_Issues': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Emergengy_Repair': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'Estimated_annual_income': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Furnace_Issues': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'HRP_Approved': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'HRP_Denied': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Home_owners_insurance': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Max_income_for_people': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'Max_income_per_person': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Meta': {'object_name': 'Home_Repair'},
            'Mo_income_Food_Assist': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Mo_income_SS': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Mo_income_SSDI': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Mo_income_TANF': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Mortage': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'Own_dwelling': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Own_multiple_props': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Package_mailed': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Package_returned': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Plumbing_Issues': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Previous_client': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Previous_when': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'Property_taxes_uptodate_city': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Property_taxes_uptodate_county': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Referred_to_HRP_by': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'Reverse_mortage': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'Smoke_detectors_needed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Total_Monthly': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Verified_Home_ownership': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'Work_completed_by_HRP': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'appliances': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.living_in_home': {
            'DOB': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Disabled': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Meta': {'object_name': 'Living_In_Home'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'relationship': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        u'MHDC.month_1': {
            'Alimony_Child_support': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Income_from_Employment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Meta': {'object_name': 'Month_1'},
            'Pension_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Rental_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'SSI_Disability': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Savings_account': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'TANF_Food_Stamps': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Total': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Unemployment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.month_2': {
            'Alimony_Child_support': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Income_from_Employment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Meta': {'object_name': 'Month_2'},
            'Pension_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Rental_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'SSI_Disability': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Savings_account': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'TANF_Food_Stamps': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Total': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Unemployment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.month_3': {
            'Alimony_Child_support': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Income_from_Employment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Meta': {'object_name': 'Month_3'},
            'Pension_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Rental_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'SSI_Disability': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Savings_account': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'TANF_Food_Stamps': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Total': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Unemployment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.month_4': {
            'Alimony_Child_support': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Income_from_Employment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Meta': {'object_name': 'Month_4'},
            'Pension_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Rental_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'SSI_Disability': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Savings_account': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'TANF_Food_Stamps': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Total': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Unemployment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.month_5': {
            'Alimony_Child_support': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Income_from_Employment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Meta': {'object_name': 'Month_5'},
            'Pension_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Rental_income': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'SSI_Disability': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Savings_account': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'TANF_Food_Stamps': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Total': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'Unemployment': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.repair_checklist': {
            'Alimony': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Bankruptcy_Documentation': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Child_support_court_order_12_month_history': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Copy_of_cleaning_for_furnace': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'County_CDBG_referral_form': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Current_Social_Security_Disability_Award_leter': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Deed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Divorce_Decree': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Drivers_license_identificaton': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Federal_tax_returns': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Food_assistance_Letter': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Letter_of_Medical_Necessity_for_Ramps': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Meta': {'object_name': 'Repair_Checklist'},
            'Most_recent_paystubs': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Purchase_of_care_letter': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Rental_income': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'TANF_letter': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Title_mobile_home': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Verification_of_unemployment_income': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.repair_internal_checklist': {
            'Alimony': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Alimony_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Appoinment_with_client': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Appoinment_with_client_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Approved_or_Denied': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Authorization_Release_Info': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Authorization_Release_Info_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Bankruptcy_Discharge_Documentation': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Bankruptcy_Discharge_Documentation_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Child_Support_Court_Order': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Child_Support_Court_Order_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Child_Support_History': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Child_Support_History_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Client_file_passed': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Copy_of_Drivers_license': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Copy_of_Drivers_license_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Copy_of_Property_Taxes': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Copy_of_Property_Taxes_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Deed': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Deed_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Denial_letter_sent': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Denial_letter_sent_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Disability_Award_letter': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Disability_Award_letter_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Divorce_Decree': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Divorce_Decree_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Eligibility_Packet_Sent': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Federal_Taxes_two_years': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Federal_Taxes_two_years_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Finalize_payment_requests': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Finalize_payment_requests_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Food_Assistance_Letter': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Food_Assistance_Letter_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Income_Elibility_Determined': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Intake_form': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Invoices_given_to_PCP': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Invoices_given_to_PCP_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Letter_sent': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Letter_sent_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Meta': {'object_name': 'Repair_Internal_Checklist'},
            'Monthly_Pension_Statements': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Monthly_Pension_Statements_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Mortage_Statement': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Mortage_Statement_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Photos_of_dwelling': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Photos_of_dwelling_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Prepare_presentation_committee': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Preservation_Manager_calls': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Preservation_Manager_calls_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Purchase_Care_Letter': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Purchase_Care_Letter_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Site_visit_worksheet': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Site_visit_worksheet_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Six_recent_Pay_stubs': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Six_recent_Pay_stubs_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Spreadsheet_on_server': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Submit_invoices_to_AD': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Submit_invoices_to_AD_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'TANF_letter': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'TANF_letter_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'Total_Eligibility_Packet_received': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Two_months_bank_Statements': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'Two_months_bank_Statements_upload': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'MHDC.selfhelpapplication': {
            'Meta': {'object_name': 'SelfHelpApplication'},
            'appEmployerAddress': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'appEmployerName': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'appEmployerprevCity': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'appEmployerprevZip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'appPrevAddress': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'appPrevCity': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'appPrevZip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'appYearsThere': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'client': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['MHDC.Client']"}),
            'co_DOB': ('django.db.models.fields.DateField', [], {}),
            'co_Mailing_State': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_Mailing_Zip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'co_Mailing_address': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_Mailing_city': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_Mailing_county': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_Ph_cell': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'co_Ph_day': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'co_Ph_evening': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'co_SSN': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'co_Years_There': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'co_appEmployerAddress': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'co_appEmployerName': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_appEmployerprevCity': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'co_appEmployerprevZip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'co_appPrevAddress': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'co_appPrevCity': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'co_appPrevZip': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'co_appYearsThere': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'co_first_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_last_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'co_middle_initial': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'crowdedHouse': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'currentArea': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'dateRecieved': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'deed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'disabilities': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'homeOwner': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'numBedrooms': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'referral': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'totalHousehold': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        u'MHDC.selfhelpstaffchecklist': {
            'Meta': {'object_name': 'SelfHelpStaffChecklist'},
            'alimony_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'alimony_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ami': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'assets_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'assets_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'bankruptcy_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'bankruptcy_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'childSupportHistory_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'childSupportHistory_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'childSupportOrder_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'childSupportOrder_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'constructionDocumentation_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'constructionDocumentation_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'counselSession_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'counselSession_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'creditPlan_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'creditPlan_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'currentArea': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'divorce_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'divorce_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'docCheckList_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'docCheckList_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'eligibility_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'eligibility_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'foodAssistance_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'foodAssistance_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'forwardSurvey_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'forwardSurvey_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ifEligible_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'ifEligible_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ifIneligible_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'ifIneligible_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'monthlyPension_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'monthlyPension_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'mortgage_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'mortgage_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'orientation_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'orientation_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'picIDs_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'picIDs_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'purchaseOfCare_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'purchaseOfCare_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recentPaystubs_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'recentPaystubs_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recentTaxes_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'recentTaxes_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'release_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'release_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'requestEstimate_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'requestEstimate_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'requestSurvey_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'requestSurvey_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'requestTitle_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'requestTitle_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reviewHUD_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'reviewHUD_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'scheduleClosing_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'scheduleClosing_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'socialSecurityLetter_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'socialSecurityLetter_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'tanfLetter_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'tanfLetter_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'totalApplication_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'totalApplication_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'totalCreditReview_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'totalCreditReview_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'updatePaystubs_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'updatePaystubs_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'usdaAppraisalRequest_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'usdaAppraisalRequest_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'usdaInterview_dateComplete': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'usdaInterview_signature': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2013, 11, 2, 5, 22, 23, 464025, tzinfo=<UTC>)'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2013, 11, 2, 5, 22, 23, 463333, tzinfo=<UTC>)'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        }
    }

    complete_apps = ['MHDC']
